using CommunityToolkit.Mvvm.Input;

namespace BestPractices.ViewModels;
using CommunityToolkit.Mvvm.ComponentModel;

public partial class HomePageViewModel : ViewModelBase
{
    [ObservableProperty]
    private string _textBlockName = "pp";
    
    // Using ObservableProperty attribute is equivalent to the following code (check out the code generated by the compiler):
    // public string TextBlockName
    // {
    //     get => _textBlockName;
    //     set
    //     {
    //         _textBlockName = value;
    //         OnPropertyChanged(); // This is implemented inside ObservableObject
    //     }
    // }
    
    [RelayCommand]
    private void ButtonOnClick()  // The RelayCommand makes it possible to make this method private
    {
        TextBlockName = "Clicked";
    } 
}