version: '3.9'

services:

  db:
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=workshop
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'


  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
